services:
  - type: web
    name: mbu-tradingbot
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: FLASK_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        # Generate one and paste it in the Render dashboard before going live
        value: ""
      - key: SQLALCHEMY_DATABASE_URI
        value: sqlite:////data/mbu.db
      - key: PAYPAL_EMAIL
        value: mbuniversal.money@hotmail.com
      - key: PAYPAL_ENV
        value: live
      - key: TRADIER_PAPER
        value: "true"
    disk:
      name: data
      mountPath: /data
      sizeGB: 1

cronJobs:
  - name: mbu-wake
    schedule: "* * * * *"
    env: docker
    plan: free
    image:
      url: alpine:3.20
    command: ["sh", "-lc", "wget -q -O- https://$RENDER_EXTERNAL_URL/wake >/dev/null 2>&1 || true"]
    # This keeps the web service warm and triggers the minute scheduler.
